// Vendors the Phosphor icons this app uses into components/Icon.tsx (inline paths: no runtime dependency, no network).
// Run: node scripts/build-icons.mjs   ·   Source: Phosphor Icons (MIT), Helena Zhang & Tobias Fried.
import { readFileSync, writeFileSync, existsSync } from "node:fs";

const SRC = "/Volumes/WorkFlow/Assets/UI Icons/phosphor-icons/SVGs";
// Every icon the app uses, by the name Phosphor gives it.
const NAMES = [
  // chrome
  "caret-right", "caret-down", "caret-left", "check", "check-circle", "wifi-slash", "x",
  "map-pin", "arrow-square-out", "share-network", "phone", "crosshair", "camera", "gear", "note-pencil", "flag", "navigation-arrow",
  // topics and item types
  "house", "cloud-sun", "car", "users-three", "traffic-cone", "traffic-signal", "tent", "student",
  "mountains", "waves", "wind", "pulse", "siren", "warning", "megaphone", "lightning-slash", "drop", "first-aid",
  "paw-print", "lightbulb-filament", "question", "bell",
];
// These also get a "<name>-fill" twin: outline is the default, fill marks the active tab and icons inside a tinted tile.
const BOTH = new Set(["house", "cloud-sun", "car", "users-three", "traffic-cone", "traffic-signal", "tent", "student",
  "mountains", "waves", "wind", "pulse", "siren", "warning", "megaphone", "lightning-slash", "drop", "first-aid", "paw-print", "lightbulb-filament", "question"]);

/** Phosphor ships `<svg viewBox="0 0 256 256">` with one <rect fill="none"> spacer and the drawing after it. Keep the drawing. */
function body(file) {
  const svg = readFileSync(file, "utf8");
  const inner = svg.replace(/^[\s\S]*?<svg[^>]*>/, "").replace(/<\/svg>\s*$/, "").replace(/<rect width="256" height="256" fill="none"\/>/, "").trim();
  // Raw SVG markup (it is injected as HTML), minus the per-shape colour: the parent <svg> supplies currentColor.
  return inner.replace(/\s*stroke="currentColor"/g, "").replace(/\s+/g, " ");
}

const entries = NAMES.flatMap((n) => {
  const out = [];
  const reg = `${SRC}/regular/${n}.svg`;
  if (!existsSync(reg)) throw new Error(`missing ${reg}`);
  out.push(`  "${n}": ${JSON.stringify(body(reg))},`);
  if (BOTH.has(n)) {
    const fill = `${SRC}/fill/${n}-fill.svg`;
    if (!existsSync(fill)) throw new Error(`missing ${fill}`);
    out.push(`  "${n}-fill": ${JSON.stringify(body(fill))},`);
  }
  return out;
});

const out = `// GENERATED by scripts/build-icons.mjs — do not edit by hand.
// Phosphor Icons (MIT) by Helena Zhang and Tobias Fried: https://phosphoricons.com
"use client";

const PATHS: Record<string, string> = {
${entries.join("\n")}
};

export type IconName = keyof typeof PATHS;

/**
 * One icon, drawn in the current text colour. Sized in rem so it follows the reader's text size,
 * unless \`px\` is given (chrome that must not grow, like the tab bar).
 */
export default function Icon({ name, size = 24, className = "", px }: { name: IconName | string; size?: number; className?: string; px?: boolean }) {
  const d = px ? { width: size, height: size } : { width: \`\${size / 16}rem\`, height: \`\${size / 16}rem\` };
  return (
    <svg viewBox="0 0 256 256" fill="currentColor" stroke="currentColor" aria-hidden focusable="false" className={\`inline-block shrink-0 \${className}\`} style={d}
      dangerouslySetInnerHTML={{ __html: PATHS[name] ?? PATHS[String(name).replace(/-fill$/, "")] ?? "" }} />
  );
}
`;
writeFileSync(new URL("../components/Icon.tsx", import.meta.url), out);
console.log(`components/Icon.tsx: ${entries.length} icons`);
