// One-time: Honolulu 911 dispatch "area" names → a point on Oʻahu, so crashes can be drawn at the neighborhood level.
// Source: OpenStreetMap Nominatim (one request per second, identified UA, per their usage policy). Output: lib/oahuAreas.ts
import { readFileSync, writeFileSync } from "node:fs";
const rows = JSON.parse(readFileSync(new URL("../fixtures/hnl-traffic.json", import.meta.url), "utf8"));
const extra = (process.argv[2] ? JSON.parse(readFileSync(process.argv[2], "utf8")) : []);
const areas = [...new Set([...rows, ...extra].map((r) => (r.area ?? "").trim()).filter(Boolean))].sort();
const out = {};
for (const a of areas) {
  // "Oahu" is not in OSM addresses; "Hawaii" + a Honolulu County filter is. Keep only hits on the island frame.
  const q = encodeURIComponent(`${a}, Honolulu County, Hawaii`);
  const res = await fetch(`https://nominatim.openstreetmap.org/search?q=${q}&format=json&limit=3`, { headers: { "User-Agent": "io (aloha@csprinkels.com)" } });
  const j = (await res.json().catch(() => [])).filter((h) => +h.lat > 21.2 && +h.lat < 21.77 && +h.lon > -158.35 && +h.lon < -157.58);
  if (j[0]) out[a] = [Number(Number(j[0].lat).toFixed(4)), Number(Number(j[0].lon).toFixed(4))];
  else console.error("no match:", a);
  await new Promise((r) => setTimeout(r, 1100));
}
const ts = `// Generated by scripts/build-areas.mjs from Honolulu 911 dispatch area names (OpenStreetMap). [lat, lon]\nexport const OAHU_AREAS: Record<string, [number, number]> = ${JSON.stringify(out, null, 2)};\n`;
writeFileSync(new URL("../lib/oahuAreas.ts", import.meta.url), ts);
console.log(`${Object.keys(out).length}/${areas.length} areas`);
